twig:
#<<<<<<< ours
#    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
#=======
    file_name_pattern: '*.twig'
#>>>>>>> theirs

when@test:
    twig:
        strict_variables: true
