language: php

php:
  - "7.4.8"

services:
  - mysql

install:
  - wget https://get.symfony.com/cli/installer -O - | bash
  - export PATH="$HOME/.symfony/bin:$PATH"
  - composer install --no-interaction
  - ./bin/console doctrine:database:create
  - ./bin/console doctrine:migration:migrate --no-interaction
  - echo "" >> .env
