language: php

php:
  - "7.4.8"

services:
  - mysql

install:
  - composer install --no-interaction
  - ./bin/console doctrine:database:create
  - ./bin/console doctrine:migration:migrate --no-interaction
  - touch .env
  - echo "" >> .env
